name: tour_buddy
description: A trip budget tracker app

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  firebase_core: ^4.3.0 # For Firebase core initialization - Adjusted version
  cloud_firestore: ^6.1.1 # For Firestore database - Adjusted version
  firebase_auth: ^6.1.3 # For user authentication - Adjusted version
  google_sign_in: ^7.2.0
  provider: ^6.0.5 # Ensure provider is also listed if you're using it - Adjusted version
  share_plus: ^12.0.1 # Adjusted version to be compatible
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  uuid: ^4.4.0
  http: ^1.2.1
  google_fonts: ^7.0.0
  local_auth: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/TourBuddylogo.png
