name: tour_buddy
description: A trip budget tracker app

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  firebase_core: ^2.25.3 # For Firebase core initialization - Adjusted version
  cloud_firestore: ^4.14.0 # For Firestore database - Adjusted version
  firebase_auth: ^4.16.0 # For user authentication - Adjusted version
  google_sign_in: ^6.1.0
  provider: ^6.0.5 # Ensure provider is also listed if you're using it - Adjusted version
  share_plus: ^8.0.0 # Adjusted version to be compatible
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  uuid: ^4.4.0
  http: ^1.2.1
  google_fonts: ^6.2.1
  local_auth: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/TourBuddylogo.png
